# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='unidades',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
