# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20171112_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='precioFinal',
            field=models.FloatField(default=0),
        ),
    ]
